server:
  port: 8848
spring:
  datasource:
    #      ???
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://81.68.70.3:3306/meChat?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    username: root
    password: Root@123

mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
#    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      #      主键生成策略
      id-type: ASSIGN_ID